############################################################################
# Copyright 2007-2022 Universidade do Porto - Faculdade de Engenharia      #
# Laboratório de Sistemas e Tecnologia Subaquática (LSTS)                  #
############################################################################
# This file is part of DUNE: Unified Navigation Environment.               #
#                                                                          #
# Commercial Licence Usage                                                 #
# Licencees holding valid commercial DUNE licences may use this file in    #
# accordance with the commercial licence agreement provided with the       #
# Software or, alternatively, in accordance with the terms contained in a  #
# written agreement between you and Universidade do Porto. For licensing   #
# terms, conditions, and further information contact lsts@fe.up.pt.        #
#                                                                          #
# European Union Public Licence - EUPL v.1.1 Usage                         #
# Alternatively, this file may be used under the terms of the EUPL,        #
# Version 1.1 only (the "Licence"), appearing in the file LICENCE.md       #
# included in the packaging of this file. You may not use this work        #
# except in compliance with the Licence. Unless required by applicable     #
# law or agreed to in writing, software distributed under the Licence is   #
# distributed on an "AS IS" basis, WITHOUT WARRANTIES OR CONDITIONS OF     #
# ANY KIND, either express or implied. See the Licence for the specific    #
# language governing permissions and limitations at                        #
# http://ec.europa.eu/idabc/eupl.html.                                     #
############################################################################
# Author: PGonçalves                                                       #
############################################################################
# 4WD configuration file.                                                  #
############################################################################

[Require asv/basic.ini]
[Require hardware/lctr-rpi/thermalzone.ini]

############################################################################
# General Parameters.                                                      #
############################################################################

[General]
Vehicle                                 = 4wd
CPU Usage - Maximum                     = 85

############################################################################
# Actuators.                                                               #
############################################################################

[Actuators.R4WD]
Enabled                                 = Always
Entity Label                            = AUXBoard
Debug Level                             = None
Activation Time                         = 0
Deactivation Time                       = 0
Serial Port - Device                    = /dev/ttyAMA0
Serial Port - Baud Rate                 = 921600
Timeout AUX Communication               = 5.0
Minimum Satellites for GPSFix state     = 4
Minimum HDop for GPSFix state           = 3.0
Channel Name 1                          = Batteries
Channel Name 2                          = CPU
Channel Name 3                          = Motors
Minimum Voltage Level                   = 9.5
Maximum Voltage Level                   = 12.6
Nominal Voltage Level                   = 11.1
Motor 1 - Entity Label                  = Motor
Distance to Stop Motors                 = 0.3
Use Data Lidar to Stop                  = false

############################################################################
# Autonomy.                                                                #
############################################################################

############################################################################
# Control.                                                                 #
############################################################################

[Control.ASV.Autopilot]
Enabled                                             = Hardware
Entity Label                                        = Heading Controller
# Enable Gain Scheduling                              = false
# Use new gains                                       = false
# Preferred scheduling                                = adcp
Enable Thrust Assistance                            = true
Enable Thrust During Turn                           = true
Thrust Assistance                                   = 1.0
Maximum Thrust Actuation                            = 1.0
Thruster Always On                                  = true
Minimum Speed for Thrust                            = 0.1
Maximum Rudder Actuation                            = 1.0
# Course PID Gains Transect                           = 0.75, 0.001, 0.0
Course PID Gains Turning                            = 0.7, 0.0, 0.0
# Ramp Actuation Limit                                = 0.0
Log PID Parcels                                     = true
Entity Label - Navigation                           = Navigation Manager
# Activate LP Filtering                               = false
# Activate N Filtering                                = false
# Activate BS Filtering                               = false
# Activate External Filtering                         = false
# External Filter Type                                = LPF
# LP taps                                             = 20
# LPF scaling                                         = 1.2
# NF taps                                             = 10
# BSF taps                                            = 10
# BSF scaling                                         = 20
# External Filter Frequency                           = 1.0
# SOG threshold - Heading Control                     = 0.2
# Gain Scheduling Interval                            = 60
# Correlation Limit                                   = 0
# Amplitude Limit                                     = 0
# Vehicle Pitch Rate Limit                            = 18
# Vehicle Roll Rate Limit                             = 20
Debug Level                                         = None

[Control.ASV.HeadingAndSpeed]
Enabled                                             = Never

[Control.ASV.RemoteOperation.DifferentialThrust]
Enabled                                             = Never

[Control.ASV.RemoteOperation.ThrusterAndRudder]
Enabled                                             = Always
Entity Label - CAS                                  = Path Control

[Control.Path.VectorField]
Enabled                                             = Never

############################################################################
# Maneuver.                                                                #
############################################################################

############################################################################
# Navigation.                                                              #
############################################################################

[Navigation.General.GPSNavigation]
Enabled                                 = Always
Entity Label                            = Navigation
Entity Label - GPS                      = AUXBoard
#Entity Label - IMU                      = AUXBoard
#Entity Label - Yaw                      = AUXBoard

[Navigation.AUV.Navigation]
Enabled                                 = Never

[Navigation.General.NavManager]
Enabled                                 = Hardware
Entity Label                            = Navigation Manager
Entity Label - Euler Angles             = AHRS
Entity Label - Angular Velocity         = AHRS
Main unit                               = GPS
Secondary unit                          = CPC
Third unit                              = AIS
Input timeout                           = 30
Debug Level                             = None

############################################################################
# Monitors.                                                                #
############################################################################

[Monitors.Clock]
Enabled                                 = Hardware
Entity Label                            = Clock
Minimum GPS Fixes                       = 30
Maximum Clock Offset                    = 2
Boot Synchronization Timeout            = 60
Hardware Clock Synchronization Command  = hwclock -w

[Monitors.CPUFan]
Enabled                                 = Always
Entity Label                            = CPU Fan
Debug Level                             = None
Activation Time                         = 0
Deactivation Time                       = 0
Fan PinOut                              = 23
Max temperature                         = 64.0
Min temperature                         = 54.0
Entity Label - Temperature              = Mainboard (Core)

[Monitors.CPURpi]
Enabled                                 = Never
Entity Label                            = CPU Monitor
Debug Level                             = None
Execution Frequency                     = 1.0
Set CPU in PowerSave                    = true
Entity Label - Temperature              = Mainboard (Core)

[Monitors.CPUScaling]
Enabled                                 = Hardware
Entity Label                            = CPU Scaling
Activation Time                         = 0
Deactivation Time                       = 0
Debug Level                             = None
Use Linux Liquorix                      = false
# Default linux kernel: powersave, ondemand, performance
# Liquorix linux kernel: ondemand, userspace, performance
Set CPU In Mode                         = ondemand
# CPU ARIES: 500MHz <> 1900MHz
Set Maximum CPU Frequency in MHz        = 500

[Monitors.Entities]
Enabled                                 = Always
Entity Label                            = Entity Monitor
Activation Time                         = 0
Deactivation Time                       = 0
Debug Level                             = None
Execution Priority                      = 10
Report Timeout                          = 5
Transition Time Gap                     = 4.0
Maximum Consecutive Transitions         = 3
Default Monitoring                      = Daemon
Default Monitoring -- Hardware          = AUXBoard

[Monitors.HostResources]
Enabled                                  = Always
Entity Label                             = Host Resources
Active                                   = true
Activation Time                          = 0
Deactivation Time                        = 0
Debug Level                              = None

[Monitors.Wifi]
Enabled                                 = Always
Entity Label                            = WiFi Monitor
Interface Name                          = wlan0
Activation Time                         = 0
Deactivation Time                       = 0
Debug Level                             = None

############################################################################
# Power.                                                                   #
############################################################################

############################################################################
# Sensors.                                                                 #
############################################################################

[Sensors.ThermalZone]
Enabled                                 = Always
Entity Label                            = Thermal Zone
Entity Label - Temperature              = Mainboard (Core)
Execution Frequency                     = 1.0

############################################################################
# Simulators.                                                              #
############################################################################

[Simulators.GPS]
Enabled                                 = Simulation
Execution Frequency                     = 1
Entity Label                            = GPS
Number of Satellites                    = 8
HACC                                    = 2
HDOP                                    = 0.9
Activation Depth                        = 0.2
Report Ground Velocity                  = false
Report Yaw                              = false
Initial Position                        = 41.1850, -8.7062

############################################################################
# Supervisors.                                                             #
############################################################################

[Supervisors.Power]
Enabled                                 = Hardware
Entity Label                            = Power Supervisor
Activation Time                         = 0
Deactivation Time                       = 0
Debug Level                             = None
Execution Priority                      = 10
Main Power Channel                      = System
Command - On Power Down                 = 
Command - On Power Down Abort           =

[Supervisors.Vehicle]
Enabled                                 = Always
Entity Label                            = Vehicle Supervisor
Activation Time                         = 0
Deactivation Time                       = 0
Debug Level                             = None
Execution Priority                      = 10
Execution Frequency                     = 2
Allows External Control                 = false
Maneuver Handling Timeout               = 1.0

############################################################################
# Transports.                                                              #
############################################################################

[Transports.Logging]
Flush Interval                          = 0.5

[Transports.CommManager]
Enabled                                 = Always
Entity Label                            = Communications Manager
Iridium Reports Period                  = 20000
Iridium - Entity Label                  = 
GSM - Entity Label                      = 
Send Iridium plain texts                = true
